name: salenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - cmocean=2.0
  - dask=2021.7.2
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - netcdf4=1.5.1.2
  - numpy=1.21.1
  - pandas=1.3.1
  - python=3.7.10
  - scipy=1.7.1
  - xarray=0.19.0
  - xskillscore

